
## ENV
export USER=`/usr/bin/whoami`
export GROUP=`/usr/bin/id -gn $user`
export MAIL="$USER@student.42.fr"
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin:$HOME/.brew/bin:$HOME/bin
export LSCOLORS="GxfxcxdxBxexdxbxbxgxgx"

if [ -f $HOME/.zshrc_bindkey ]; then
	. $HOME/.zshrc_bindkey
fi

if [ -f $HOME/.zshrc_aliases ]; then
	. $HOME/.zshrc_aliases
fi

## HISTORY CONFIG
HISTFILE=~/.zshrc_history
SAVEHIST=1000
HISTSIZE=1000
setopt append_history
setopt inc_append_history
setopt hist_ignore_dups
setopt hist_expire_dups_first
setopt hist_reduce_blanks
setopt hist_find_no_dups
setopt share_history

## AUTO COMPLETION

zmodload 'zsh/complist'
setopt hist_verify
setopt auto_remove_slash
setopt chase_links

unsetopt list_ambiguous
unsetopt glob_dots

zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh_cache

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors '${(s.:.)LSCOLORS}'
#zstyle ':completion:*:manuals' separate-sections true
#zstyle ':completion:*:manuals.(^1*)' insert-sections true

autoload -U compinit && compinit

## PROMPT

autoload colors; colors

#autoload -Uz vcs_info
#setopt prompt_subst

PROMPT="%B%{$fg[cyan]%}["
if [[ -n $SSH_CLIENT ]]; then
	PROMPT+="%{$fg[red]%}ssh:"
fi
PROMPT+="%{$fg[blue]%}%n@%M%{$fg[cyan]%}]["

PROMPT+="%{$fg[yellow]%}%1~%{$fg[cyan]%}] %b%{$reset_color%}"

RPROMPT="%B%{$fg[cyan]%}[%{$fg[red]%}%D{%a %e, %b %G - %R}%{$fg[cyan]%}]%b%{$reset_color%}"
